# Generated by Django 2.2.5 on 2019-10-31 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Get_username', models.CharField(max_length=100, null=True)),
                ('Get_eqm_id', models.IntegerField(default=0)),
                ('Get_Amount', models.IntegerField(default=0)),
                ('Br_code', models.CharField(max_length=100, null=True)),
                ('date_br', models.DateField(default=datetime.date(2019, 10, 31), verbose_name='date published')),
                ('Date_repatriate', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Table_equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eqm_name', models.CharField(max_length=200)),
                ('Eqm_model', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Date_add', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail', models.TextField()),
                ('Img', imagekit.models.fields.ProcessedImageField(upload_to='Eqm_images/')),
                ('Eqm_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Table_equipment')),
            ],
        ),
    ]
