# Generated by Django 2.2.5 on 2019-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_borrow_get_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='Get_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
