# Generated by Django 2.2.5 on 2019-10-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_borrow_get_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='Get_username',
            new_name='username',
        ),
    ]
