# Generated by Django 2.2.5 on 2019-10-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20191101_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='Get_username_id',
            new_name='Get_username',
        ),
    ]
