# Generated by Django 2.2.5 on 2019-10-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20191101_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='Last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
