# Generated by Django 2.2.5 on 2019-11-02 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_borrow_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='Get_eqm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_br',
            field=models.DateField(default=datetime.date(2019, 11, 2), verbose_name='date published'),
        ),
    ]
