# Generated by Django 2.2.5 on 2019-11-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_borro_order_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borro_order',
            name='Get_eqm_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Table_equipment'),
        ),
    ]
