# Generated by Django 2.2.5 on 2019-11-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20191105_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borro_order',
            name='Eqm_name',
        ),
    ]
